# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CircleciMigrate < Formula
  desc "CLI to migrate CircleCI organizations (contexts, projects, secrets) between orgs"
  homepage "https://github.com/AwesomeCICD/circleci-org-migration-cli"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AwesomeCICD/circleci-org-migration-cli/releases/download/v0.11.0/circleci-migrate_0.11.0_darwin_amd64.tar.gz"
      sha256 "b6a8aaa37d21d5a6731577c57b337fa9a7771787b7f462dfc439cee15e93588a"

      def install
        bin.install "circleci-migrate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AwesomeCICD/circleci-org-migration-cli/releases/download/v0.11.0/circleci-migrate_0.11.0_darwin_arm64.tar.gz"
      sha256 "84efc99f8fb6ccf23c554ec7b1a1e5dce31190c4d851c0eeeeb9ab87767f4b3b"

      def install
        bin.install "circleci-migrate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/AwesomeCICD/circleci-org-migration-cli/releases/download/v0.11.0/circleci-migrate_0.11.0_linux_amd64.tar.gz"
      sha256 "5f84968d903acdde4fe7360c904a1748d62eba4285db4c16e23a564a17c35d18"
      def install
        bin.install "circleci-migrate"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/AwesomeCICD/circleci-org-migration-cli/releases/download/v0.11.0/circleci-migrate_0.11.0_linux_arm64.tar.gz"
      sha256 "0895edd5020320ad4985e0c6779e8fd721adb0c0cfd5cde9174cd95fe81d6216"
      def install
        bin.install "circleci-migrate"
      end
    end
  end

  test do
    system "#{bin}/circleci-migrate version"
  end
end
